export const MOVIES_REQUEST = "MOVIES_REQUEST";
export const MOVIES_REQUEST_SUCCESS = "MOVIES_REQUEST_SUCCESS";
export const MOVIES_REQUEST_FAILED = "MOVIES_REQUEST_FAILED";
export const MOVIE_DETAIL_REQUEST = "MOVIE_DETAIL_REQUEST";
export const MOVIE_DETAIL_SUCCESS = "MOVIE_DETAIL_SUCCESS";
export const MOVIE_DETAIL_FAILED = "MOVIE_DETAIL_FAILED";
